name: panet-build

on:
  push:
    branches: [ '*' ]
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate PaNET_metadata.ttl
        uses: vemonet/jena-riot-action@v3.14
        with:
          input: source/PaNET_metadata.ttl

  build:
    runs-on: ubuntu-latest
    container:
      image: gitlab.desy.de:5555/paul.millar/panet-build:v0.6

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to identify non-tagged builds

      - name: Work-around for broken support for safe.directory
        run: /usr/bin/git config --global --add safe.directory `pwd`

      - name: Build PaNET and documentation
        run: /bin/build-panet -d

      - name: Archive generated PaNET
        uses: actions/upload-artifact@v4
        with:
          name: PaNET
          path: |
            source/PaNET.owl
            source/PaNET_reasoned.owl
          retention-days: 7

      - name: Upload documentation as artifact
        id: upload-docs-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: widoco/
          retention-days: 7

  deploy:
    # From naming convention on above tag selection, tags
    # only trigger the workflow if they are releases.
    if: ${{ github.ref_type == 'tag' }}
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4