name: widoco

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for all branches
on: 
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Download widoco
      run: mkdir widoco && wget -O widoco/widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.14/widoco-1.4.14-jar-with-dependencies.jar
  
    - name: Compile documentation
      run: |
        cd widoco        
        java -jar ./widoco.jar \
        -ontFile ../source/PaNET.owl \
        -oops \
        -webVowl \
        -includeAnnotationProperties \
        -outFolder doc/ \
        -rewriteAll \
        -confFile ../source/widoco.config \
        -includeImportedOntologies \
        -uniteSections \
        -excludeIntroduction
        #cp -r ./doc/* ../doc
        cd ..

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull
        # Delete previous documentation to avoid conflict before merging to the remote branch
        git rm -r --ignore-unmatch ./doc/.
        git commit -m "Removing previous documenation"
        cp -r widoco/doc/* ./doc
        git rm -r --ignore-unmatch ./widoco/.
        git add ./doc/.
        git commit -m "Add changes to the ontology documentation" -a
        git push
     
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
